version: '3.1'

services:
  lanparty-seating:
    build:
      context: .
    environment:
      PORT: 4000
      MIX_ENV: prod
    ports:
      - "4000:4000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
